import { StyleSheet } from "react-native";
import { C } from "../../assets";

export const GuestCountStyleSheet = StyleSheet.create({
  container: {
    flexDirection: "row",
    width: "95%",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 14,
    alignItems: "center",
    borderRadius: 10,
    backgroundColor: C.colors.primary.color1,
    height: 60,
    marginBottom: 20,
    marginTop: 20,
    zIndex: 2,
    alignSelf: "center",
    elevation: 3,
    shadowColor: C.colors.bg.shadow1,
    shadowRadius: 3,
    shadowOpacity: 0.4,
    borderBottomWidth: 0.2,
    borderColor: C.colors.border.dark,
    shadowOffset: { width: 1, height: 1 },
  },
  heading: { fontSize: 16, fontWeight: "bold", color: C.colors.text.black },
  counterContainer: {
    flexDirection: "row",
    backgroundColor: C.colors.primary.color4,
    borderRadius: 5,
    height: 24,
  },
  btn: {
    width: 15,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  textInput: {
    backgroundColor: C.colors.primary.color1,
    fontSize: 14,
    width: 40,
    height: 24,
    padding: 0,
    textAlign: "center",
    color: C.colors.text.black,
    fontWeight: "bold",
  },
  arrow: {
    height: 15,
    width: 15,
  },
  leftArrow: {
    left: -2,
  },
  rightArrow: {
    transform: [{ rotateZ: "180deg" }],
    left: 2,
  },
  maxCountWarningContainer: {
    position: "absolute",
    right: 0,
    top: 33,
    backgroundColor: C.colors.primary.color1,
    borderRadius: 5,
    elevation: 5,
    width: 250,
    height: 30,
    shadowRadius: 3,
    shadowOpacity: 0.4,
    borderBottomWidth: 0.2,
    borderColor: C.colors.border.dark,
    shadowOffset: { width: 1, height: 1 },
  },
  maxCountWrapper: {
    backgroundColor: C.colors.primary.color1,
    width: 15,
    height: 15,
    position: "absolute",
    right: 5,
    transform: [{ rotateZ: "45deg" }],
    top: -5,
    zIndex: 0,
    elevation: 5,
  },
  maxCountWarningBox: {
    flex: 1,
    zIndex: 2,
    backgroundColor: C.colors.primary.color1,
    position: "absolute",
    width: 250,
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 5,
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingVertical: 5,
    height: 30,
    borderColor: C.colors.border.dark,
  },
  textContainer: {
    borderWidth: 1.1,
    width: 11,
    height: 11,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  i: { fontSize: 8, lineHeight: 9, color: C.colors.text.black },
  warning: { fontSize: 12, lineHeight: 14, color: C.colors.text.black },
});
