import { C } from "../../assets";
import { StyleSheet } from "react-native";
import colors from "../../assets/values/colors";

const HEADER_IMAGE_WIDTH = C.measures.SCREEN_WIDTH;
const HEADER_IMAGE_HEIGHT = C.measures.SCREEN_HEIGHT / 3;

export const storeStyles = StyleSheet.create({
  bg: {
    backgroundColor: C.colors.primary.color1,
  },
  image: {
    width: HEADER_IMAGE_WIDTH,
    height: HEADER_IMAGE_HEIGHT,
  },
  share: {
    width: 30,
    height: 30,
    marginTop: -15,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 25,
  },
  linear: {
    width: "100%",
    flexDirection: "row",
    position: "absolute",
    justifyContent: "space-between",
  },
  topTouch: {
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  favIcon: {
    marginTop: -17,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  nonFavIcon: {
    marginTop: -17,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  btnContainer: {
    height: 35,
    width: 35,
    backgroundColor: "rgba(26, 26, 26, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
  },
  overViewCard: {
    padding: 10,
    width: "95%",
    marginTop: -25,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    borderRadius: C.measures.BORDER_RADIUS,
    backgroundColor: C.colors.primary.color1,
  },
  titleTxt: {
    fontSize: 18,
    marginBottom: 5,
    fontWeight: "700",
    color: C.colors.text.black,
    flex: 7,
    height: "100%",
  },
  txtMed: {
    fontSize: 16,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  placeTxt: {
    fontSize: 14,
    marginTop: 2,
    maxWidth: "90%",
    marginBottom: 10,
    fontWeight: "500",
    color: C.colors.text.darkGry,
  },
  descTxt: {
    fontSize: 14,
    marginBottom: 5,
    maxWidth: "90%",
    fontWeight: "500",
    letterSpacing: -0.8,
    color: C.colors.text.darkGry,
  },
  timeTxt: {
    fontSize: 14,
    marginBottom: 10,
    fontWeight: "700",
    color: C.colors.text.darkGry,
  },
  btnStyle: {
    marginRight: 10,
    paddingLeft: 20,
    paddingRight: 20,
  },
  mb: {
    marginBottom: 10,
  },
  iconStyle: {
    padding: 5,
    paddingRight: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollStyle: {
    padding: 15,
    width: "100%",
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 150,
  },
  offerListStyle: {
    paddingRight: 150,
  },
  cardTxtView: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    padding: 30,
    width: "100%",
    height: "100%",
    position: "absolute",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  shareTxt: {
    fontSize: 17,
    fontWeight: "600",
    letterSpacing: -0.7,
    color: C.colors.primary.color1,
  },
  shareTxtUpp: {
    fontSize: 18,
    maxWidth: 200,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: C.colors.primary.color1,
  },
  txtV: {
    alignItems: "flex-start",
    justifyContent: "center",
  },
  icon: {
    width: 50,
    right: 10,
    height: 50,
    borderRadius: 90,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.colors.primary.color1,
  },
  locContainer: {
    padding: 20,
    width: "95%",
    marginTop: 10,
    alignSelf: "center",
    borderRadius: C.measures.BORDER_RADIUS,
    backgroundColor: C.colors.primary.color1,
  },
  cabBtn: {
    paddingLeft: 20,
    paddingRight: 20,
  },
  locTxt: {
    fontSize: 18,
    fontWeight: "600",
    color: C.colors.text.darkGry,
  },
  locDescTxt: {
    fontSize: 12,
    marginLeft: 5,
    fontWeight: "600",
    letterSpacing: -0.5,
    color: C.colors.text.darkGry,
  },
  dotStyle: {
    top: -60,
  },
  map: {
    height: 150,
    width: "100%",
    borderRadius: 10,
  },
  cardSpacer: {
    marginTop: 10,
    marginBottom: 5,
  },
  shareImg: {
    height: 180,
    width: C.measures.SCREEN_WIDTH,
  },

  paginator: {
    alignSelf: "center",
    position: "absolute",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    top: HEADER_IMAGE_HEIGHT - 40,
  },
  imageIcon: {
    width: 8,
    height: 8,
    marginRight: 10,
    borderRadius: 90,
    backgroundColor: C.colors.primary.color1,
  },
  activeImage: {
    backgroundColor: C.colors.primary.secondary,
  },
  ratingText: {
    fontSize: 20,
    marginTop: 5,
    lineHeight: 20,
    marginLeft: 10,
  },
  mb10: {
    marginBottom: 10,
  },
  storeTimeCard: {
    // borderWidth: 1,
    borderRadius: 10,
    alignSelf: "flex-start",
    // borderColor: C.colors.text.darkGry,
    width: C.measures.SCREEN_WIDTH / 1.3,
    // backgroundColor: "green",
  },
  timing: {
    fontSize: 16,
    color: "black",
    fontWeight: "500",
  },
  error: {
    color: C.colors.text.red,
  },
  tabIcon: {
    flex: 1,
    marginRight: 5,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.colors.primary.color2,
  },
  featureCard: {
    width: "50%",
    padding: 8,
    paddingLeft: 0,
    alignItems: "center",
    flexDirection: "row",
  },
  circle: {
    width: 10,
    height: 10,
    marginRight: 10,
    borderRadius: 90,
    backgroundColor: C.colors.primary.color2,
  },
  txtDark: {
    fontSize: 14,
    fontWeight: "500",
    color: C.colors.primary.color2,
  },
  mt20: {
    marginTop: 20,
  },
  mT10: {
    marginTop: 10,
  },
  offerCard: {
    height: 130,
    marginLeft: -20,
    alignItems: "center",
    justifyContent: "center",
    width: C.measures.SCREEN_WIDTH,
  },
  offerImage: {
    top: 0,
    height: 130,
    width: "90%",
    borderRadius: 20,
    position: "absolute",
  },
  verticalText: {
    left: 30,
    top: "48%",
    fontSize: 14,
    fontWeight: "500",
    alignSelf: "center",
    position: "absolute",
    textTransform: "uppercase",
    color: C.colors.primary.color1,
    transform: [{ rotate: "270deg" }],
  },
  whtTxt: {
    fontSize: 16,
    fontWeight: "600",
    color: C.colors.primary.color1,
  },
  moreBtn: {
    padding: 5,
    marginTop: 10,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  whiteTxt: {
    fontSize: 12,
    fontWeight: "600",
    color: C.colors.primary.color1,
  },
  bookNowBtn: {
    right: 10,
    bottom: 10,
    height: 40,
    width: 120,
    position: "absolute",
  },
  titleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    alignItems: "flex-end",
  },
  infoBtn: {
    justifyContent: "center",
  },
  toolIcon: {
    resizeMode: "contain",
  },
  bookCabBtn: {
    width: "30%",
    height: 35,
    borderWidth: 1,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  cabBtnTxt: {
    color: colors.primary.color2,
    fontSize: 15,
    fontWeight: "400",
  },
  dayItems: {
    width: C.measures.SCREEN_WIDTH / 1.4,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: 5,
    paddingRight: 20,
    marginBottom: 15,
    alignItems: "center",
  },
  ratingContainer: {
    flex: 1.5,
    backgroundColor: C.colors.primary.color2,
    borderTopEndRadius: 15,
    borderTopStartRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  starIcon: {
    width: "30%",
    height: "30%",
    resizeMode: "contain",
    tintColor: "gold",
  },
  gIconContainer: {
    flex: 1.8,
    justifyContent: "center",
    alignItems: "center",
  },
  gIcon: { width: "70%", height: "70%", resizeMode: "contain" },
});
