import { StyleSheet } from "react-native";
import { C } from "../../assets";

export const mobileRegisterPageStyles = StyleSheet.create({
  inputBox: { borderRadius: 10, borderWidth: 1 },
  inputContainer: { alignSelf: "center", marginBottom: 20 },
  container: {
    backgroundColor: C.colors.primary.color1,
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
  },
  shadedBackground: {
    width: "100%",
    height: C.measures.SCREEN_HEIGHT_WS,
    flex: 1,
    position: "absolute",
    backgroundColor: C.colors.bg.shadow3,
    zIndex: 2,
  },
  progressContainer: { flex: 1, width: "100%" },
  progressWrapper: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  iconContainer: {
    width: 15,
    height: 15,
    borderRadius: 10,
    padding: 2,
    borderWidth: 1.3,
  },
  line: { width: 50, height: 2, borderRadius: 8 },
  otpScreenContainer: { width: "100%", alignItems: "center" },
  otpTitleContainer: {
    marginBottom: 40,
    marginTop: 50,
    width: "90%",
    justifyContent: "center",
  },
  titleText: {
    fontWeight: "bold",
    fontSize: 18,
    paddingVertical: 10,
    color: C.colors.text.black,
  },
  description: { fontSize: 11, color: C.colors.text.dark },
  otpComponent: { width: "100%", height: 180 },
  editPhoneIconContainer: {
    position: "absolute",
    zIndex: 3,
    left: 200,
    top: 7,
  },
  otpInputContainer: {
    width: "100%",
    position: "absolute",
    height: 130,
    alignItems: "center",
    justifyContent: "center",
    top: 50,
  },
  errorText: {
    fontSize: 12,
    position: "absolute",
    top: 70,
    color: C.colors.text.red,
  },
  btnContainer: {
    flexDirection: "row",
    width: "75%",
    justifyContent: "space-around",
    marginTop: 30,
  },
  btnCommonStyle: {
    width: 80,
    height: 35,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  cancelBtn: {
    borderWidth: 1,
    borderColor: C.colors.border.dark,
  },
  mainBtn: {
    backgroundColor: C.colors.primary.secondary,
  },
  cancelbtnText: {
    fontWeight: "bold",
    color: C.colors.text.black,
    textTransform: "capitalize",
  },
  mainBtnText: {
    color: C.colors.text.color1,
    fontWeight: "bold",
    textTransform: "capitalize",
  },
  successScreenContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
  },
  successScreenWrapper: {
    marginTop: "35%",
    alignItems: "center",
  },
  imageStyle: {
    height: C.measures.SCREEN_WIDTH / 2.5,
    width: C.measures.SCREEN_WIDTH / 2.5,
  },
  successTitile: {
    marginBottom: 5,
    marginTop: 30,
    fontSize: 16,
    fontWeight: "bold",
    color: C.colors.text.black,
  },
  successDescription: {
    marginBottom: 10,
    fontSize: 12,
    color: C.colors.text.dark,
  },
  continueBtn: {
    width: "90%",
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.colors.primary.secondary,
    borderRadius: 5,
  },
  continueBtnText: {
    fontWeight: "bold",
    color: C.colors.text.color1,
    textTransform: "capitalize",
  },
  confirmModalContainer: {
    flex: 1,
    justifyContent: "flex-end",
  },
  confirmationDialogContainer: {
    width: "100%",
    height: 250,
    backgroundColor: C.colors.primary.color1,
    elevation: 25,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    alignItems: "center",
  },
  dialogTitleContainer: { width: "90%", alignItems: "center", paddingTop: 15 },
  confirmTitleText: {
    fontSize: 18,
    fontWeight: "bold",
    color: C.colors.text.black,
  },
  otpDialogDescription: {
    paddingTop: 10,
    textAlign: "center",
    lineHeight: 20,
    letterSpacing: 0.5,
    color: C.colors.text.dark,
  },
  phoneNumber: { fontSize: 18, fontWeight: "bold", paddingTop: 20 },
});
