import { StyleSheet } from "react-native";
import { C } from "../../assets";

export const historyCardStyle = StyleSheet.create({
  buttondiv: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "100%",
  },
  bottomview: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  innerButton: {
    backgroundColor: "#E8BCA4",
    color: "black",
    marginHorizontal: 5,
    borderRadius: 5,
    width: "auto",
    paddingHorizontal: 4,
  },
  innerButtonRight: {
    backgroundColor: C.colors.primary.color2,
    marginHorizontal: 5,
    borderRadius: 5,
    width: "auto",
    paddingHorizontal: 4,

    text: {
      color: C.colors.text.color1,
      padding: 3,
      textTransform: "capitalize",
      fontFamily: C.strings.ARCHIVO_NARROW_BOLD,
    },
  },
  innerButtonTxt: {
    fontSize: 13,
    fontWeight: "600",
    padding: 3,
  },
  cardView: {
    width: "80%",
    height: 140,
    borderWidth: 3,
    borderRadius: 6,
    borderColor: C.colors.border.drkGrey,
    borderStyle: "solid",
    marginTop: 24,
    borderLeftWidth: 8,
  },
  cardViewDescription: {
    width: "90%",
    marginLeft: "auto",
    marginRight: "auto",
    height: 150,
    borderWidth: 1,
    borderRadius: 12,
    borderColor: C.colors.border.drkGrey,
    marginTop: 35,
    borderLeftWidth: 8,
    display: "flex",
    flexDirection: "row",
    backgroundColor: C.colors.primary.color1,
  },
  Heading: {
    marginLeft: 20,
    fontSize: 20,
    fontFamily: "Times New Roman",
    marginTop: 20,
    fontWeight: "800",
    color: "black",
  },
  Image: {
    margin: 20,
    width: 100,
    height: 100,
    borderRadius: 8,
    resizeMode: "cover",
    borderWidth: 1,
  },
  ImageIcon: {
    margin: 3,
    width: 15,
    height: 15,
    resizeMode: "center",
  },

  Description: {
    display: "flex",
    color: "black",
    marginTop: 20,
    width: 150,
    height: 100,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  DescriptionRow: {
    display: "flex",
    width: 80,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  MultiLineText: {
    height: 80,
    marginTop: 12,
    marginLeft: 12,
    borderWidth: 0,
    padding: 10,
  },
  container: {
    width: "100%",
    height: "100%",
    backgroundColor: "white",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 10,
  },
  goBackBtn: {
    alignItems: "center",
    marginLeft: 20,
    width: "100%",
    height: 40,

    justifyContent: "flex-start",
    flexDirection: "row",
    marginBottom: 5,
  },
  textInput: {
    width: "80%",
    height: 50,
    borderColor: C.colors.border.drkGrey,
    borderStyle: "solid",
    marginTop: 15,
    fontSize: 20,
    borderBottomWidth: 2,
  },
  button: {
    width: "80%",
    height: 40,
    backgroundColor: C.colors.primary.color2,
    marginTop: 25,
    padding: 5,
    fontSize: 20,
    color: "white",
  },
  norTexSty: {
    color: C.colors.text.grey,
    fontSize: 14,
  },
  comFonSty: {
    // fontFamily: "Archivo Narrow",
    lineHeight: 20,
    fontFamily: C.strings.ARCHIVO_NARROW_BOLD,
  },
  ImageSK: {
    margin: 20,
    width: 100,
    height: 100,
    borderRadius: 8,
    resizeMode: "center",
    overflow: "hidden",
  },
  StoreName: {
    width: 120,
    marginLeft: 4,
    color: C.colors.text.grey,
    textTransform: "capitalize",
    fontFamily: C.strings.ARCHIVO_NARROW_BOLD,
  },
  DetailsBtn: {
    backgroundColor: C.colors.primary.primary4,
    width: 70,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
  },
  detailsBtnText: {
    color: C.colors.text.color1,
    lineHeight: 18,
    textTransform: "capitalize",
    fontFamily: C.strings.ARCHIVO_NARROW_BOLD,
  },
});
