import { StyleSheet } from "react-native";
import fonts from "../../assets/values/fonts";
import measures from "../../assets/values/measures";
import { C } from "../../assets";

export const calendarStyles = StyleSheet.create({
  datePickerWrapper: {
    borderRadius: 10,
    borderColor: C.colors.primary.color2,
    borderWidth: 2,
    width: 55,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  dayHeaderContainer: {
    alignItems: "center",
    padding: 10,
  },
  selectedDayText: {
    color: C.colors.text.color1,
  },
  unSelectedDayText: {
    color: C.colors.text.black,
  },
  selectedDayBackground: {
    backgroundColor: C.colors.primary.color2,
  },
  day: { fontWeight: "bold" },
  month: { fontSize: 16 },
  date: { fontWeight: "bold", fontSize: 20, textAlign: "center" },
  seperator: { height: 2, backgroundColor: C.colors.primary.color2 },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 30,
    width: 60,
  },
  navigationButton: {
    borderRadius: 5,
    borderRadius: 10,
    fontSize: 10,
    width: 40,
    height: 40,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  timeSlotsContainer: {
    // borderWidth: 1,
    //borderRadius: 10,
    //borderColor: "black",
    backgroundColor: C.colors.primary.color1,
    padding: 10,
    /*  elevation: 5,
    zIndex: 5,
    shadowColor: "black",
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 10, */
  },
  timeSlotWrapper: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  timeSlot: {
    borderRadius: 25,
    margin: 5,
    elevation: 2,
    borderWidth: 0.3,
    zIndex: 5,
    shadowColor: C.colors.primary.color2,
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    width: 100,
    marginVertical: 10,
    flexDirection: "row",
    overflow: "hidden",
  },
  timeSlotSelected: {
    color: C.colors.text.color1,
    backgroundColor: C.colors.primary.color2,
  },
  timeSlotUnSelected: {
    color: C.colors.text.black,
    borderColor: C.colors.border.dark,
    backgroundColor: C.colors.primary.color1,
  },
  overlay: {
    flex: 1,
    backgroundColor: C.colors.bg.shadow3, // Adjust the alpha value for the desired opacity
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: C.colors.primary.color1,
    borderRadius: 10,
    padding: 20,
    width: measures.SCREEN_WIDTH - 40,
  },
  calendar: {
    padding: 20,
    zIndex: 1,
  },
  calendarBtnContainer: {
    flexDirection: "row",
    marginTop: 30,
    justifyContent: "space-around",
    alignSelf: "center",
    width: "80%",
  },
  calendarBtn: {
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    width: 100,
  },
  calendarCancelBtn: {
    backgroundColor: C.colors.primary.color2,
    borderWidth: 1,
    borderColor: C.colors.primary.color1,
  },
  btnText: {
    fontWeight: "bold",
    fontSize: 18,
    textAlign: "center",
    textTransform: "capitalize",
  },
  calendarCancelBtnText: { color: C.colors.text.color1 },
  calendarConfirmBtnText: { color: C.colors.text.black },
  container: {
    width: "100%",
    flex: 1,
    backgroundColor: C.colors.primary.color1,
  },
  DatePicker: {
    width: "95%",
    alignItems: "center",
    alignSelf: "center",
    paddingVertical: 10,
    borderRadius: C.measures.BORDER_RADIUS,
    marginTop: 20,
    elevation: 3,
    shadowOpacity: 0.4,
    borderColor: C.colors.border.dark,
    shadowOffset: { width: 1, height: 1 },
    shadowColor: C.colors.bg.shadow1,
    backgroundColor: C.colors.primary.color1,
  },
  datePickerTitleContainer: {
    width: "100%",
    alignItems: "center",
  },
  datePickerTitleText: {
    textAlign: "center",
    marginBottom: 10,
    fontWeight: "bold",
    color: C.colors.text.black,
  },
  dateChipsContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  calendarToggle: {
    marginLeft: "20%",
    marginTop: 3,
    height: 30,
    width: "60%",
  },
  navigationIcon: { height: 20, width: 20 },
  calendarIcon: { height: 30, width: 30 },
  slotSelectorContainer: {
    width: "95%",
    alignItems: "center",
    alignSelf: "center",
    paddingVertical: 10,
    borderRadius: C.measures.BORDER_RADIUS,
    marginTop: 20,
    elevation: 3,
    shadowOpacity: 0.4,
    borderColor: C.colors.border.dark,
    shadowOffset: { width: 1, height: 1 },
    shadowColor: C.colors.bg.shadow1,
    backgroundColor: C.colors.primary.color1,
  },
  continueBtnContainer: {
    width: "100%",
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "flex-end",
    marginBottom: 10,
  },
  continueBtn: {
    borderRadius: 10,
    paddingTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 10,
    height: 45,
    width: "95%",
    alignSelf: "center",
  },
  continueBtnText: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "600",
    color: C.colors.text.color1,
  },
});
