import { Dimensions, StyleSheet } from "react-native";
import { C } from "../../assets";

export const TBTimeSlotsStyles = StyleSheet.create({
  topContainer: {
    justifyContent: "flex-end",
    marginTop: 20,
    backgroundColor: C.colors.primary.color1,
    borderRadius: 10,
    width: "95%",
    alignSelf: "center",
    elevation: 2,
    shadowColor: C.colors.bg.shadow1,
    shadowRadius: 3,
    shadowOpacity: 0.4,
    borderBottomWidth: 0.2,
    borderColor: C.colors.border.dark,
    shadowOffset: { width: 1, height: 1 },
  },
  container: {
    height: 210,
    width: "100%",

    paddingHorizontal: 10,
  },
  heading: { fontSize: 16, fontWeight: "bold", color: C.colors.text.black },
  quickViewContainer: {
    width: "100%",
    alignItems: "center",
    height: 50,
    justifyContent: "center",
  },
  quickViewBtnWrapper: {
    width: 160,
    flexDirection: "row",
    justifyContent: "space-around",
    height: 30,
    borderWidth: 1,
    paddingHorizontal: 10,
    alignItems: "center",
    borderRadius: 10,
  },
  qvBtnText: { fontSize: 18, fontWeight: "bold" },
  slotSelectorContainer: { width: "100%", alignItems: "center" },
  slotSelectorWrapper: {
    borderWidth: 1,
    flexDirection: "row",
    width: 110,
    borderRadius: 10,
    overflow: "hidden",
    height: 100,
  },
  slotSelectorView: {
    flexDirection: "row",
    position: "absolute",
    flex: 1,
    height: 100,
    top: 0,
  },
  singleSlotSlectWrapper: {
    width: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  singleSlotSelector: {
    width: 44,
    height: 100,
    fontSize: 30,
    fontWeight: "bold",
    textAlign: "center",
  },
  middleDiv: {
    alignSelf: "center",
    fontSize: 30,
    fontWeight: "bold",
    width: 10,
    textAlign: "center",
    lineHeight: 32,
  },
  infoBtn: {
    height: 40,
    width: 15,
    justifyContent: "center",
  },
  toolIcon: {
    height: 14,
    width: 14,
    resizeMode: "contain",
  },
  bottomContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  toolTipContainer: {
    alignItems: "flex-start",
    width: Dimensions.get("window").width - 50,
    height: 150,
  },
  ToolTipTitle: {
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
    color: C.colors.primary.color2,
    alignSelf: "center",
    marginBottom: 10,
  },
  timeSlotContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    height: "70%",
  },
  timeSlotWrapper: {
    borderWidth: 1,
    borderColor: C.colors.border.grey,
    padding: 10,
    borderRadius: 10,
  },
  sessionText: {
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    color: C.colors.text.black,
    marginBottom: 5,
  },
  normalText: {
    fontSize: 12,
    fontWeight: "400",
    textAlign: "center",
    color: C.colors.text.black,
    marginBottom: 5,
  },
  timeSlotTitle: { flexDirection: "row", alignItems: "center" },
  iText: {
    fontSize: 12,
    marginRight: 5,
    lineHeight: 15,
    color: C.colors.text.dark,
  },
});
